Fix run_CMU when running with the flag --from_poses
cvg/pixloc pull request #24
Opened 2021-12-02 15:35 UTC by fulkast

This PR relates to #23, which faces a similar issue on the Aachen dataset.

The fix adds a field `log_path` to the `Path` class and populates the corresponding setup for the run_CMU.py file.

2021-12-03 15:16 UTC, Skydes requested changes
This should also be switched to `hloc_logs`:
https://github.com/cvg/pixloc/blob/bec9b29b1edd08a1219d5a085bc7776072546ee3/pixloc/localization/localizer.py#L145

2021-12-03 15:16 UTC, Skydes commented on pixloc/utils/data.py
> +    log_path: Optional[Path] = None
The path entry is actually `hloc_logs` and already exists. I'd rather use this name instead.

2021-12-03 15:16 UTC, Skydes commented on pixloc/run_CMU.py
> +    log_path='slice{slice}/CMU_hloc_superpoint+superglue_netvlad10.txt_logs.pkl',
Use `hloc_logs` instead.

2021-12-05 10:38 UTC, fulkast commented
Thanks for clarifying, I wasn't sure I could reuse `hloc_logs`. I've now made the updates

2021-12-08 00:15 UTC, merged